# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'sixLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sixLive
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8'

  target 'sixLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sixLiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
